config/routes.rb
Rails.application.routes.draw do
  
  root to: 'members/words#index'

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :members, controllers: {
    sessions:      'members/sessions',
    passwords:     'members/passwords',
    registrations: 'members/registrations'
  }

  #devise_for :users, controllers: {
    #sessions: 'users/sessions'}

  namespace :admins do
    resources :genres, except: [:destroy]
  end

  scope module: :members do
    resources :words do
      resource :likes, only: [:destroy, :create]
    end
    resources :members, except: [:index, :new, :destroy]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GIRL</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <% if member_signed_in? %>
            <li>ガルメン</li>
            <li><%= link_to "ログアウト", destroy_member_session_path, method: :delete %></li>
          <% elsif admin_signed_in? %>
            <li>管理者</li>
            <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
          <% else %>
            <li>ゲスト</li>
            <li><%= link_to "新規登録", new_member_registration_path %></li>
            <li><%= link_to "ログイン", new_member_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>